### ISSUE TITLE
Custom data type support

### ISSUE THREAD

**Issue by craigedmunds** [flyvictor/fortune#125]
Fortune uses mongoose schema to describe the resources. A number of built in data types exist, like String, Date, Number and these can be assembled into resources and sub resources, etc.

In our usage of fortune we have a number of other datatypes that we use across our instances, for example prices, where we store the amount, and the currency it's in:

.resource("resource-name", {
  field1 : String,
  price : {
    amount : Number,
    currency : String
  }
}

Rather than re-define this within each resource and field it's used, it should be possible to instead define the price field as being of type "price", and fortune to take care of the plumbing:

.resource("resource-name", {
  field1 : String,
  price : "price"
}

**Comment by Azzoo** [comment]
I propose 3 mechanisms to do this:
I choosed third.

  1. User register a resource for the custom type earlier than use it, but it should use special string syntax.

        //User is registering a resource for the custom type
        .resource("price-type", {
             amount : Number,
             currency : String
        });

        //User described model for the custom type using special syntax:
        .resource("ring", {
            material : String,
            price : "customtype:price-type"
        });

  2. User register a resource for the custom type earlier than use it, but it should use special object syntax.

        //User is registering a resource for the custom type
        .resource("price-type", {
             amount : Number,
             currency : String
        });

        //User described model for the custom type using special syntax:
        .resource("ring", {
            material : String,
            price : {customtype:"price-type"}
        });


  3. User register a custom data type using a different function, then it will be able to use it like relation.

         //User is registering a custom type
         .customType("price-type", {
         amount : Number,
         currency : String
         });

         //User described model for the custom type using special syntax:
         .resource("ring", {
         material : String,
         price : "price-type"
         });


In the .resource method the custom type should be checked and place the correct structure instead of "price-type".

**Comment by Azzoo** [comment]
Submitted pull request, which realized following use case:

var fortune = require('./fortune')
, app = fortune({
db: 'petstore'
})
.customType('price', {
amount: Number,
units: String
})
.resource('person', {
name: String,
age: Number,
pets: ['pet'] // "has many" relationship to pets
})
.resource('pet', {
name: String,
age: Number,
owner: 'person', // "belongs to" relationship to a person
cost: 'price'
})
.listen(1339);

**Comment by craigedmunds** [comment]
PR is https://github.com/flyvictor/fortune/pull/134
