### ISSUE TITLE
Request validation

### ISSUE THREAD

**Issue by craigedmunds** [flyvictor/fortune#126]
Introduce a mechanism within fortune to validate requests.

The rules for a field should be declared as part of the field definition within the resource, and all requests (POST/PATCH/GET) should first be validated and rejected where they don't pass.

Mongoose built in validation framework could work in our case, need to try it though.

**Comment by craigedmunds** [comment]
Going to be looked at by Paulius 17/4

**Comment by paranoidyuppie** [comment]
Decided to go with validate.js as a validation engine.

This would be connected to a beforeWrite hook and throw an error if resource doesn't validate.

For now this would support POST, PUT and PATCH (replace only)

The rules could be set inline inside schema:

`name: { type: String, validation: { presence: true } }`

As well as defined with `app.addValidator(name, constraint)` and used as strings:

`app.addValidator('exist', { presence: true })`
`name: { type: String, validation: 'exist' }`

Several rules can be applied to a single field if needed:

`name: { type: String, validation: ['exist', {length : { minimum: 2 } } ] }`
